name: Docker Image CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - name: Login to docker hub
      uses: docker/login-action@v2.0.0
      if: github.event_name != 'pull_request'
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v3.6.2
      id: meta
      with:
          images: atom63/qt-docker 
          
    - name: Build and push      
      uses: docker/build-push-action@v2.10.0
      with:  
          file: ./x86_64/buster/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: atom63/qt-docker:linux-buster-x86_64
          labels: ${{ steps.meta.outputs.labels }}

  build_cross:

    runs-on: ubuntu-latest
    needs: build_base
    
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - name: Login to docker hub
      uses: docker/login-action@v2.0.0
      if: github.event_name != 'pull_request'
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v3.6.2
      id: meta
      with:
          images: atom63/qt-docker 
          
    - name: Build and push      
      uses: docker/build-push-action@v2.10.0
      with:  
          file: ./cross/x86_64_armv7a/buster/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: atom63/qt-docker:linux-buster-cross-x86_64-armv7a
          labels: ${{ steps.meta.outputs.labels }}          
